### ISSUE TITLE
Uncaught TypeError: root.load is not a function

### ISSUE THREAD

**Issue by 07ARB** [protobufjs/protobuf.js#1223]
protobuf.js version: 6.8.8

i am trying to update Protobufjs from 5.0.1 to 6.8.8
during calling of `load(filename, root, callback)` function i am getting this error

```
Uncaught TypeError: root.load is not a function
```

```
ProtoBuf.load("/576b572d5ab6bfa1e3ebd2ff36e82df2.proto", "*.proto",null);
```

```
function load(filename, root, callback) {
    if (typeof root === "function") {
        callback = root;
        root = new protobuf.Root();
    } else if (!root)
        root = new protobuf.Root(); <------  Uncaught TypeError: root.load is not a function
    return root.load(filename, callback);
}
```

```
ScModule.proto = ProtoBuf.load(wsProto, "webswing.proto",null);
```

![Call stack](https://user-images.githubusercontent.com/8948111/57919432-6f685400-78b6-11e9-8137-8a7f2eec38f5.png)

**Comment by alexander-fenster** [comment]
Hi @07ARB,

The second argument of the `load` function must be either a callback that will be called when your proto file is loaded, or an instance of `protobuf.Root`. It must not be a string anyway, that's why it is failing.

Here is the code example of using `load`: https://github.com/protobufjs/protobuf.js#using-proto-files

Let us know if the code sample does not work for you!

**Comment by rajeshmajumdar** [comment]
var protobuf = require('protobufjs')

protobuf.load('protofile.proto',  (err, root) = () => {
    // do something
})

This code is throwing an error, `protobuf.load is not a function`.

I am new to this, I don't know what I am doing wrong here.
