### ISSUE TITLE
Why AwesomeMessage.verify(payload); doesn't verify incomplete or invalid at all ?

### ISSUE THREAD

**Issue by ajfg93** [protobufjs/protobuf.js#1504]
protobuf.js version: protobufjs@6.10.1

`AwesomeMessage.verify(payload);` doesn't work as expected. It doesn't verify incomplete or invalid at all.

Modify the official example code as an example:

`awesome.proto`: 

```
package awesomepackage;
syntax = "proto3";

message AwesomeMessage {
    string awesome_field = 1; // becomes awesomeField
}

```

```
var protobuf = require('protobufjs');
protobuf.load("awesome.proto", function(err, root) {
    if (err)
        throw err;

    // Obtain a message type
    var AwesomeMessage = root.lookupType("awesomepackage.AwesomeMessage");

    // Exemplary payload
    var payload1 = { awesome: "AwesomeString" };
    var payload2 = { awesome: "AwesomeString", blablabla: 3 };
    // Verify the payload if necessary (i.e. when possibly incomplete or invalid)
    var errMsg1 = AwesomeMessage.verify(payload1);
    if (errMsg1)
        throw Error(errMsg1);

    var errMsg2 = AwesomeMessage.verify(payload2);
    if (errMsg2)
        throw Error(errMsg2);
});
```
both `errMsg1` and `errMsg2` are `null`. No error is produced.

**Comment by murgatroid99** [comment]
Both of those payload objects are valid `AwesomeMessage` message representations. An object is invalid if it contains fields from the message type that are represented incorrectly. Neither of those objects contains the `awesomeField` field, so there is no possible validation failure.

It is valid to omit fields because all fields in `proto3` are optional. And fields that aren't defined in the message are simply ignored.
