### ISSUE TITLE
Equivalent of SerializeToString

### ISSUE THREAD

**Issue by Nithanaroy** [protobufjs/protobuf.js#1515]
protobuf.js version: latest

What is the equivalent function to https://googleapis.dev/python/protobuf/latest/google/protobuf/message.html#google.protobuf.message.Message.SerializeToString here?

https://colab.research.google.com/drive/1pf-5SEtuyI2dobAuRHECcHv02zR5lCiU?usp=sharing has the Python implementation, which I'm trying to find an alternative in node.js using protobufjs

**Comment by alexander-fenster** [comment]
@Nithanaroy If you have a `Message` to serialize:

```js
const root = protobuf.loadSync('/path/to/file.proto');
// OR: const root = protobuf.Root.fromJSON('/path/to/file.json'); if you have file.json generated by pbjs tool
const Message = root.lookup('Message');
const buffer = Message.encode({ field: "value"}).finish();
```

Does it work for you?

**Comment by alexander-fenster** [comment]
I looked at your code example - the difference between Python and protobuf.js here is that Python operates with the generated stubs produced by `protoc` - someone got a `*.proto` file, used `protoc` to generate `*.py` files out of them, and then imported those `*.py` from the Python code.

In protobuf.js, you will either need to load `*.proto` during the runtime (as I do in my sample), or use `pbjs` (instead of `protoc`) to produce a `*.js` or `*.json` file and load it.

If you point me to TF proto that describes the `Example`, `Feature`, etc., I can show you how to do it.

(also, it's really unclear why you would play with Tensorflow messages in JavaScript :)   but it's up to you of course!)

**Comment by Nithanaroy** [comment]
Hi Alex,

Thanks for the ideas.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/example/feature.proto
and
https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/core/example/example.proto
are the proto files.

I'm also not clear on what serialization of,
features { feature { key: "country" value { bytes_list { value: "us" } } } }
produces,
b'\n\x13\n\x11\n\x07country\x12\x06\n\x04\n\x02us'
a binary python string. Ultimately I want to pass {"country": "us"} to a
tensorflow.js API as a binary string like above.

--
Nitin @ LinkedIn <http://bit.ly/nitinpasumarthy>

**Comment by Nithanaroy** [comment]
You might already know this, but
https://github.com/protocolbuffers/protobuf/blob/367f3d831ee3186035a14f871cbcbc1b028b6b9a/python/google/protobuf/internal/python_message.py#L1091
is the Python implementation, whose alternative I'm looking for in
protobuf.js or in JS

--
Nitin @ LinkedIn <http://bit.ly/nitinpasumarthy>

**Comment by alexander-fenster** [comment]
@Nithanaroy This code will work:

```
const protobuf = require("protobufjs");
const root = protobuf.loadSync("./example.proto");const Example = root.lookup("Example");
const example = Example.fromObject({
  features: {    feature: {
      country: {
        bytesList: {          value: [
            Buffer.from('us', 'latin1')
          ]
        },
        kind: 'bytesList'
      }
    }
  }
});
const buffer = Example.encode(example).finish();
console.log(buffer);
```

I updated your colab (I don't know if it's possible to run Node.js samples from that notebook, but I created a separate `sample.js` there that produces the same binary buffer as Python does).

Pre-requisites:
- put proto files in the same folder (I changed an import path in `example.proto` so I don't need to create a deep directory tree;
- `npm install protobufjs`.

**Comment by Nithanaroy** [comment]
Thanks a lot Alex. This works like a charm. However when I integrated with
the rest of the tensorflow.js code, it fails as the serialized string is
different from the Python equivalent,
https://googleapis.dev/python/protobuf/latest/google/protobuf/message.html#google.protobuf.message.Message.SerializeToString
.
Yes, colab doesn't run node.js code. I created a shared playground at
https://repl.it/join/rssuxvmf-nitinpasumarthy which enables you to run and
fork the code.

Thanks again for your help.

--
Nitin @ LinkedIn <http://bit.ly/nitinpasumarthy>

**Comment by Nithanaroy** [comment]
What is the correct way to serialize this Buffer object as a binary string
in JS?

--
Nitin @ LinkedIn <http://bit.ly/nitinpasumarthy>

**Comment by alexander-fenster** [comment]
After an offline discussion @Nithanaroy figured out with Tensorflow developers that it won't be possible to pass a serialized protobuf to TF.js. More details [here](https://groups.google.com/a/tensorflow.org/g/tfjs/c/EFANYfSpwq4/m/zd7YLcJ-AAAJ).  Since it's not related to protobuf.js, I'm going to close this issue for now.
