### ISSUE TITLE
Don't set defaults for optional fields

### ISSUE THREAD

**Issue by rakyll** [protobufjs/protobuf.js#179]
Protobuf.js shouldn't set defaults for optional fields while encoding a message, rather set defaults during decoding if not present -- and provide has('fieldname') to help users to distingush if it's an explicit set or set by default. I'm not able to use this module to talk to Google's Datastore API.

**Comment by dougrad** [comment]
Primitive accessors should always return a value even for optional fields.

The ProtoBuf.js implemention of default values violates this compared to the C++ and Go protobuf libs. It seems like the problem is trying to make direct field accesses give the same result as calling the accessor function; in C++/Go they do not.

The actual fields should always store the explicit value if present during deserialize or stored by an setter.  The spec does not say that the default value should be **stored** -- just that it should be returned by the accessor if there was a null value stored.

In addition, ProtoBuf.js violates the last paragraph of the spec that AoJ quoted in above.  For primitive fields without a default value, the accessor does not return the type-specific default.

To be true to ProtoBuf author's intentions, getters/accessors should be generated as:

    get_xyz() {
       if ('xyz' in this and this.xyz != null)
          return this['xyz'];
       if (proto has default value for xyz) 
          return proto default;
       return type-specific default.
    }

**Comment by jeremyong** [comment]
Out of curiosity, why was this closed? As far as I can tell, this is still an issue. I'm not sure I understand the design decision to not inject default values if not present (and subsequently ignore default values when encoding). Or at least provide the default value in the message prototype.

**Comment by Cristy94** [comment]
Any updates? 

This is very annoying when used with TypeScript, because the type definition says it can be undefined (being an optional field), but it is never undefined as the default value will be (for strings) empty string. Currently multiple bugs occurred because I was checking `stringVariable !== undefined` instead of the (inintuitive) `stringVariable !== ''`. It's even worse when trying to send optional integers (trying to send both 0 and undefined will both be 0 on the receiving end).

**Comment by dcodeIO** [comment]
Well, this is from 2014. Things have changed a lot since then. If you have a specific issue with the current version, please open a new issue.

**Comment by Cristy94** [comment]
Ok, thanks! I think it is strange that this issue was closed even though the problem was never fixed. 
 
  On Tue, Dec 26, 2017 at 1:43, Daniel Wirtz<notifications@github.com> wrote:   
Well, this is from 2014. Things have changed a lot since then. If you have a specific issue with the current version, please open a new issue.
