### ISSUE TITLE
fixed64 encode/decode missmatch

### ISSUE THREAD

**Issue by luckslovez** [protobufjs/protobuf.js#1827]
protobuf.js version: 7.1.2

I have a proto message with a single field `fixed64`. For certain numbers, there is a missmatch between the encoded and decoded objects.

I've created [this repo](https://github.com/luckslovez/protobufjs-fixed64) as reference, to execute it just run
```sh
$ npm i
$ node index.js
```
It contains an `awesome.proto` and `index.js` files. 

```proto
// awesome.proto
syntax = "proto3";
package awesomepackage;

message AwesomeMessage {
  fixed64 awesome_num = 1;
}
```
```js
// index.js
const protobuf = require('protobufjs');

protobuf.load("awesome.proto", function (err, root) {
    const AwesomeMessage = root.lookupType("awesomepackage.AwesomeMessage");
    const payload = {awesomeNum: 1666189808901000000};

    const message = AwesomeMessage.create(payload);
    console.log(JSON.stringify(message)); //output: { awesomeNum: 1666189808901000000 }

    const buffer = AwesomeMessage.encode(message).finish();

    const decodedMessage = AwesomeMessage.decode(buffer);
    console.log(JSON.stringify(decodedMessage)); //output: { awesomeNum: 1666189808900999936 }
});
```
Why is there a missmatch in `awesomeNum`? Is that expected? What am I missing?

In case it is of any help, this is how the generated `AwesomeMessage#encode` looks like:
```js
(function anonymous(Writer,types,util
) {
return function AwesomeMessage$encode(m,w){
  if(!w)
  w=Writer.create()
  if(m.awesomeNum!=null&&Object.hasOwnProperty.call(m,"awesomeNum"))
  w.uint32(9).fixed64(m.awesomeNum)
  return w
}
})
```
Should not that `uint32` be an `uint64`?

Any help will be much appreciated! Thanks for this awesome library!

**Comment by acode-x** [comment]
Hi @luckslovez 

I am not totally aware of the library internal implementation. I guess the logic could be:
uint32(9) - would refer to the position of awesome_num in AwesomeMessage
fixed64(m.awesomeNum) - the actual value

Regarding mismatch - awesomeNum is due to Number object in javascript.
You may only get precision upto `(2^53)-1` (aka `Number.MAX_SAFE_INTEGER`).
References: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger

If you have values > (2^53)-1, it is recommended to use long.js library as given in this repo README.md

**Comment by luckslovez** [comment]
Note for myself **Read the docs!**. Thank you so much, it works perfectly with `long.js`!
```js
// index.js
const protobuf = require('protobufjs');
const long = require('long');

protobuf.load("awesome.proto", function (err, root) {
    const AwesomeMessage = root.lookupType("awesomepackage.AwesomeMessage");
    const awesomeNum = long.fromString("1666189808901000000");
    const payload = {awesomeNum};

    const message = AwesomeMessage.create(payload);
    console.log(JSON.stringify(message)); //output: { awesomeNum: 1666189808901000000 }

    const buffer = AwesomeMessage.encode(message).finish();

    const decodedMessage = AwesomeMessage.decode(buffer);
    console.log(JSON.stringify(decodedMessage)); //output: { awesomeNum: 1666189808901000000 }
    // ALL GOOD! https://github.com/protobufjs/protobuf.js/issues/1827
});
```
