### ISSUE TITLE
CVE-2023-36665 - Fix not reflected in dist version

### ISSUE THREAD

**Issue by wakester25** [protobufjs/protobuf.js#1918]
protobuf.js version: 7.2.4

**Expected Behavior** : Fix introduced for CVE-2023-36665 (https://github.com/protobufjs/protobuf.js/releases/tag/protobufjs-v7.2.4) would also be reflected in the distribution version of the code as well 

**Actual Behavior** : Fix does not seem to be rolled out to distribution version. Distribution version seems to be last compiled on September 9 2022  - https://cdn.jsdelivr.net/npm/protobufjs@7.2.4/dist/protobuf.js

### Code snippet from https://cdn.jsdelivr.net/npm/protobufjs@7.2.4/dist/protobuf.js
Would expect below to match https://github.com/protobufjs/protobuf.js/commit/e66379f451b0393c27d87b37fa7d271619e16b0d
```js
util.setProperty = function setProperty(dst, path, value) {
    function setProp(dst, path, value) {
        var part = path.shift();
        if (part === "__proto__") {
          return dst;
        }
        if (path.length > 0) {
```

**Comment by CalebBoLiuPriceline** [comment]
Any update?

**Comment by albertosaito** [comment]
BTW, I'm still getting CVE-2023-36665 as a security vulnerability from protobufjs@6.11.4, even when I see the code change in the dist files: https://cdn.jsdelivr.net/npm/protobufjs@6.11.4/dist/protobuf.js

Furthermore, the affected version range here https://nvd.nist.gov/vuln/detail/CVE-2023-36665 show as if everything below 7.2.4 is vulnerable.

**Comment by alexander-fenster** [comment]
That's weird, because the dist files are supposed to be rebuilt in the `prepublish` step. I'm looking at what might be wrong here.

In any case, in the latest versions (7.2.5 and 6.11.4) the dist files are fixed, I checked both of them.

The GitHub advisory https://github.com/advisories/GHSA-h755-8qp9-cq85 was updated to list 6.11.4 as fixed. If anyone knows how to update the advisory at https://nvd.nist.gov/vuln/detail/CVE-2023-36665 accordingly, please let me know, or just go ahead and do it.

**Comment by Fotiman** [comment]
I'm still getting CVE-2023-36665 detected in 7.2.5.

**Comment by imdangodaane** [comment]
Is there any news on this? I'm still getting report from scanning tools 😭
